import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import '@/app/globals.css';
import StoreProvider from '@/app/StoreProvider';
import React from 'react';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';

const font = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark, variables: { colorPrimary: 'red', colorBackground: 'rgb(55,65,81)' } }}>
      <html lang="en">
        <body className={`${font.className} flex min-h-screen justify-center items-center`}>
          <StoreProvider>
            {children}
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
