import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import '@/app/globals.css';
import StoreProvider from '@/app/StoreProvider';
import React from 'react';

const font = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
